#!/bin/bash

main()
{
  source ./configuration.conf
  source ./bash_modules/test_generate.sh

  source ./bash_modules/dialog.sh
  dialog_welcome
  dialog_brief
  dialog_project_name
  dialog_function_name
  local value
  local end_test

  for (( i = 0; i < ${#START_VALUE[@]}; i++)); do
    value=${START_VALUE[$i]}
    end_test=$(( ${FIRST_TEST_NUMBER[$i]} + 100))
    generate_case ${i} >> "${TEST_FUNCTION}_suite.c"
    generate_list_for_header ${i} >> s21_test_${FUNCTION}.h

    for (( j = ${FIRST_TEST_NUMBER[i]}; j < end_test; j++ )); do
      
      generate_tcase ${j} >> "${TEST_FUNCTION}_suite.c"

      compile ${value}
      
      generate_test ${value} ${j} >> "${TEST_FUNCTION}.c"

      value=$(echo "${value} + ${STEP[$i]}" | bc)

      if [[ ${value:0:1} == "." ]]; then
        value="0${value}"
      fi

    done
  done

  generate_end >> "${TEST_FUNCTION}_suite.c"
}
main
